### ISSUE TITLE
Effect on progress of offline miners

### ISSUE THREAD

**Issue by anorth** [filecoin-project/consensus#69]
During the 0.2.1 devnet release, a crash bug caused a large amount of miner power to go offline at around the same time. During this period, we observed extremely slow network progress (although there was [another issue](https://github.com/filecoin-project/go-filecoin/issues/2782) also contributing to that).

While perhaps unlikely, what is the expected behaviour in this situation? Is progress expected to be proportional to the amount of mining power that is actually attempting to mine blocks? Are there mechanisms other than foregone block rewards to guarantee progress?

See some [discussion in slack] (https://filecoinproject.slack.com/archives/CEHHJNJS3/p1557367076276300)

Please forgive and redirect me if this isn't the right forum for the question.

**Comment by sternhenri** [comment]
This is indeed the right forum. I expect @whyrusleeping and @ZenGround0 will have thoughts as well. 

The short answer is that block time remains 30 seconds (or X) in all cases, but expected progress will go away if some sizeable portion of the network goes offline for a time (as you saw) since it is more likely that null blocks be mined during that period.

Liveness is something that EC guarantees (ie eventual progress), and you would expect to see speed increase again as soon as the offline miners get slashed for not submitting proofs and that is reflected in the power table (ie max(proving period, power table lookback)). This could be on the order of a few thousand blocks (eg). Changing that number is doable but needs to be seen in the context of security implications (a good job for a network calculator @porcuquine).

A second avenue might be for us to add some other sort of "difficulty" related to number of null blocks (as compared to expectation) to increase or decrease the expected number of winners in EC based on such events, but it would largely have the same effect on speed as the above (albeit potentially on shorter time scales), with potential security issues that may not be worth the trouble (I'm thinking about selfish mining here or general coalition forming, eg)...

Does that answer your question @anorth ?

**Comment by anorth** [comment]
I think so, let me try to restate things.
- The block height should keep ticking away at once every 30s, but there may be many more null blocks due to foregone tickets
- If blocks are not full, this should have no significant effect on transaction throughput
- When miners fail to submit PoST, they are eventually (hours to days) considered not to actually have the claimed storage, and hence their power and chance of winning a ticket reduced
- If a miner continues to post PoST but refuses to mine blocks, there's no penalty beyond the lost block reward.

In the near term we expect the block reward to be sufficient incentive. When block reward drops, we expect gas fees to provide that incentive, priced by the gas market.

**Comment by sternhenri** [comment]
I have some nit comments about some of what you've said, but in general we're on the same page. 

Now for the nit:
- The null blocks are not due to foregone tickets but to the fact that a portion of the power in the network isn't mining. So the "on expectation 1 block per round" will drop to less than a block.
- I don't understand what you mean by "full." I believe this will have an impact on transaction throughput: null block means no transactions in that round (or 30 second time interval). However, the network will eventually correct for new power (ie slash the absent miners) thereby restoring the old throughput. 
- Exactly right. Hence the above correction.
- This is true, though it doesn't make much economic sense for an eligible miner not to mine a block...

In the near term we expect block rewards to suffice, in the long term, we expect fees (not just gas fees but also transaction fees) to make up for it yes. Though I personally don't know much about gas in FIL.

**Comment by whyrusleeping** [comment]
+1 to @henri's repsonses. Also note, this effect is not unique. If half the bitcoin network drops off, blocks will take twice as long to mine until the difficulty adjustment (once every two weeks).

**Comment by anorth** [comment]
Thanks
